### ISSUE TITLE
Azure-pipeline sample script should not continue when errors occur during tests

### ISSUE THREAD

**Issue by Mafti** [OutSystems/outsystems-pipeline#25]
Hi,

the current yaml is continuing even though there are errors in the evaluating tests task.
So a failed "test" will still result in a deployment to acceptance.
This should not be the case

**Comment by duarte-castano** [comment]
Hi @Mafti 

We do that so we are able to display the results on Azure DevOps Pipeline Tests tab.

The template uses the evaluate_test_results to generate the test report and, on the next task, publishes the result to the Pipeline Test tab (that then fails the pipeline execution if there's any failed test).

Best Regards,
Duarte
