### ISSUE TITLE
Azure DevOps Outsystems-pipeline 0.6.0 build error 

### ISSUE THREAD

**Issue by ado-os-user** [OutSystems/outsystems-pipeline#55]
Installing OutSystems Pipeline Package is successfull with 0.6.0

Collecting xunitparser==1.3.4 (from outsystems-pipeline==0.6.0)

But Fetch Lifetime Data task is failing with below error

LifeTimeHostname : The term 'LifeTimeHostname' is not recognized as the name of a cmdlet, function, script file, or 
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try 
again.

![image](https://user-images.githubusercontent.com/132485294/235986275-9de7dc6c-0101-4ad6-85ac-2fb616c0c180.png)

**Comment by duarte-castano** [comment]
Hello @ado-os-user, 

The `fetch_lifetime_data` script was not modified for this version of the package (0.6.0).
Just to be sure, I've tested the script and it works as expected.

If you think the new version of the package is impacting your pipeline, you can lock the desired version when installing it.
Example: `pip install outsystems-pipeline==0.5.0` 

Have you double-checked if the variables in the Variable Group are correctly configured?
Have you double-checked if the variables within the script call match the ones in the Variable Group?

Here is the script call that worked for me:

```
  - script: >
      python -m outsystems.pipeline.fetch_lifetime_data
      --artifacts "$(Artifacts.Folder)" 
      --lt_url $(LifeTime.Hostname) 
      --lt_token $(LifeTime.ServiceAccountToken) 
      --lt_api_version $(LifeTime.APIVersion) 
    displayName: 'Fetch LifeTime Data'
```

Also, you may have interest in our new template that uses [Mulistage pipelines in Azure DevOps](https://github.com/OutSystems/outsystems-pipeline/wiki/Building-an-OutSystems-pipeline-with-Azure-DevOps-Multistage-Pipeline)

**Comment by ado-os-user** [comment]
Hello @duarte-castano,

Thank you for the response.

I have verified all the variables and variable groups. 
Everything is in place and I tried re-run today.
Fetch Lifetime task got succeeded. 
![image](https://user-images.githubusercontent.com/132485294/236287306-1e1e868b-0610-458a-a0a2-a7f64b0c284d.png)


However, there seem to be an issue with Deploy task. 

Please refer the screenshot below:

![image](https://user-images.githubusercontent.com/132485294/236285846-4c99dcf2-8538-48de-984a-4e32055199bc.png)



Could you please help me with the issue.
