### ISSUE TITLE
Outdated Outsytems documentation URLS

### ISSUE THREAD

**Issue by df-gss** [OutSystems/outsystems-pipeline#59]
The wiki contains an outdated documentation url.

[Register LifeTime authentication token as secret variable - Devops](https://github.com/OutSystems/outsystems-pipeline/wiki/Building-an-OutSystems-pipeline-with-Azure-DevOps#22-register-lifetime-authentication-token-as-secret-variable)

The url should be updated to https://success.outsystems.com/documentation/11/reference/outsystems_apis/lifetime_api_v2/rest_api_authentication/#creating-a-service-account

**Comment by duarte-castano** [comment]
Thank you for the feedback, meanwhile we have created new step-by-step documentation for [Azure DevOps multistage pipelines](https://github.com/OutSystems/outsystems-pipeline/wiki/Building-an-OutSystems-pipeline-with-Azure-DevOps-Multistage-Pipeline)
