### ISSUE TITLE
List all artifacts in a module for Sast-integration-api branch

### ISSUE THREAD

**Issue by Cristianrage** [OutSystems/outsystems-pipeline#60]
Hello, we are trying to list all the artifacts when we are downloading the sources with the [fetch_apps_source_code.py] from the Outsystems Platform of Toyota Argentina. Is there any way like an option for that .py script or other .py script that makes that?

**Comment by duarte-castano** [comment]
Hello, @Cristianrage. The fetch_apps_source_code.py script does not include a feature to list all artifacts.
Is there anything preventing you from listing all of the files/artifacts after using the script?
