### ISSUE TITLE
Wiki Error when setting up YAML pipeline

### ISSUE THREAD

**Issue by basdejong95** [OutSystems/outsystems-pipeline#67]
Hi, we are currently implementing the Azure Devops Multistage YAML pipeline. However we found that the wiki does not contain a crucial part when trying to authenticate with Azure Devops.

https://github.com/OutSystems/outsystems-pipeline/wiki/Building-an-OutSystems-pipeline-with-Azure-DevOps-Multistage-Pipeline#53-configure-the-plugin-default-server-settings

It should be stated that the username field must be filled in with a space when using a PAT token in the password field. This is due to a limitation of the ardoHTTP plugin that will not send the authentication trough if the username field is left empty. 

```

            if (creds.UserName != "")
            {
                if (!pre_auth) // use default .NET behavior
                {
                    req.Credentials = creds;
                }
                else // send credentials with the first request (basic authentication only)
                {
                    req.Headers["Authorization"] = "Basic " +
                        Encode64(creds.UserName + ":" + creds.Password);
                }
            }

```

In the ArdoHTTP component there is no Else Branch to execute if the username is left empty. 

Can you please clarify in the wiki that this is necessary, or update the trigger pipeline to consume the Azure Devops REST api trough the normal REST consume component of outsystems (which works perfectly)

**Comment by duarte-castano** [comment]
Hi @basdejong95 , thank you for the feedback. we just updated the documentation in that regard.

Cheers,
Duarte
