### ISSUE TITLE
Unable to pass ai mentor studio check if module has been ignored 

### ISSUE THREAD

**Issue by basdejong95** [OutSystems/outsystems-pipeline#70]
Hi,
When trying to deploy an ignored module in ai mentor studio, the script will give a 404 not found exception. In my opinion it should continue the pipeline.

Kind regards,
Bas

**Comment by duarte-castano** [comment]
Hi @basdejong95,

We were able to reproduce that behavior, the script has been fixed and is now available in the recently released [outsystems-pipeline 0.8.0 python package](https://pypi.org/project/outsystems-pipeline/0.8.0/).

Cheers,
Duarte Castaño

**Comment by basdejong95** [comment]
Thanks!
